// import {ClerkProvider} from "@clerk/nextjs";
// import "./globals.css";
// import {Outfit} from 'next/font/google'
// import Provider from "./provider";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const outfit=Outfit({subsets:['latin']})

// export default function RootLayout({ children }) {
//   return (
//     <ClerkProvider>
//     <html lang="en">
//       <body
//         className={outfit.className}
//       >
//         <Provider>
//           {children}
//         </Provider>
        
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }

import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Outfit } from "next/font/google";
import Provider from "./provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      frontendApi={process.env.NEXT_PUBLIC_CLERK_FRONTEND_API}
    >
      <html lang="en">
        <body className={outfit.className}>
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
